name: kasir_jeruk_ayang
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  firebase_core: ^2.24.2
  get_storage: any
  firebase_auth: any
  cloud_firestore: any
  flutter_svg: any
  intl: any
  image_picker: any
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

